jobs:
    include:
        -   os: windows
            language: node_js
            node_js: "14"
            before_script: 
            -   cd frontend-stack-bubbling
            script:
            -   npm install
            -   CI='' npm run build
        -   language: python
            python: "3.9"
            before_script: 
            -   cd backend-stack-bubbling
            -   pip install flask
            -   pip install flask_restful
            -   pip install pymongo
            -   pip install flask_cors
            -   pip install flask_jwt_extended
            -   pip install uuid
            -   pip install pymongo[srv]
            -   set FLASK_APP=app.py
            script:
            -   pytest test_app.py
            