jobs:
    include:
        -   os: windows
            language: node_js
            node_js: "14"
            before_script: 
            -   cd frontend-stack-bubbling
            script:
            -   npm install
            -   CI='' npm run build
        -   language: python
            python: "3.9"
            before_script: 
            -   cd backend-stack-bubbling
            -   pip install -r requirements.txt
            -   pip install pymongo[srv]
            script:
            -   pytest test_app.py -p no:warnings
            -   pytest app.py -p no:warnings
            